export interface IIndiaPostCode {
    "pin": number,
    "office": string,
    "office_type": string,
    "delivery": string,
    "division": string,
    "region": string,
    "circle": string,
    "taluk": string,
    "district": string,
    "state_id": 2,
    "phone": string,
    "related_suboffice": string,
    "related_headoffice": string,
    "longitude": string,
    "latitude": string,
}